---
title: "Engagingness in Music: a Computational Analysis"
output:
  flexdashboard::flex_dashboard:
    orientation: rows  
    theme:
      version: 4
      bootswatch: superhero
    css: stylesheet.css
---
```{r table, echo=FALSE}
library(knitr)
compmus <- read.csv('compmus2025_classcorpus.csv')
compmus_dance <- read.csv('selected_dance_tracks.csv')
kable(head(compmus, 5))
kable(head(compmus_dance, 5))
```

# can we classify AI made songs? 

##

```{r classification knn, fig.width=14, fig.height=5}
library(tidyverse)
library(tidymodels)
library(ggdendro)
library(heatmaply)
get_conf_mat <- function(fit) {
  outcome <- .get_tune_outcome_names(fit)
  fit |> 
    collect_predictions() |> 
    conf_mat(truth = outcome, estimate = .pred_class)
}  

get_pr <- function(fit) {
  fit |> 
    conf_mat_resampled() |> 
    group_by(Prediction) |> mutate(precision = Freq / sum(Freq)) |> 
    group_by(Truth) |> mutate(recall = Freq / sum(Freq)) |> 
    ungroup() |> filter(Prediction == Truth) |> 
    select(class = Prediction, precision, recall)
}  

source("compmus_FV.R")

compmus2025_filtered <- 
  compmus_dance |> filter(!is.na(ai)) |> 
  mutate(ai = factor(if_else(ai, "AI", "Non-AI")))

compmus_cv <- compmus2025_filtered |> vfold_cv(5)

classification_recipe <-
  recipe(
    ai ~
      arousal +
      danceability +
      instrumentalness +
      tempo +
      valence,
    data = compmus2025_filtered
  ) |>
  step_center(all_predictors()) |>
  step_scale(all_predictors())      # Converts to z-scores.
  # step_range(all_predictors())    # Sets range to [0, 1].

knn_model <-
  nearest_neighbor(neighbors = 1) |>
  set_mode("classification") |> 
  set_engine("kknn")
classification_knn <- 
  workflow() |> 
  add_recipe(classification_recipe) |> 
  add_model(knn_model) |> 
  fit_resamples(compmus_cv, control = control_resamples(save_pred = TRUE))

classification_knn |> 
  get_conf_mat() |> 
  autoplot(type = "heatmap") +
  labs(title = "Confusion Matrix for KNN Classifier")

classification_knn |> get_pr()
```
above you can see

## 

```{r classification RF, fig.width=14, fig.height=5}
library(tidyverse)
library(tidymodels)
library(ggdendro)
library(heatmaply)
source("compmus_FV.R")
library(gridExtra)

get_conf_mat <- function(fit) {
  outcome <- .get_tune_outcome_names(fit)
  fit |> 
    collect_predictions() |> 
    conf_mat(truth = outcome, estimate = .pred_class)
}  

get_pr <- function(fit) {
  fit |> 
    conf_mat_resampled() |> 
    group_by(Prediction) |> mutate(precision = Freq / sum(Freq)) |> 
    group_by(Truth) |> mutate(recall = Freq / sum(Freq)) |> 
    ungroup() |> filter(Prediction == Truth) |> 
    select(class = Prediction, precision, recall)
}  

compmus2025_filtered <- 
  compmus_dance |> filter(!is.na(ai)) |> 
  mutate(ai = factor(if_else(ai, "AI", "Non-AI")))

compmus_cv <- compmus2025_filtered |> vfold_cv(5)

forest_model <-
  rand_forest() |>
  set_mode("classification") |> 
  set_engine("ranger", importance = "impurity")

indie_forest <- 
  workflow() |> 
  add_recipe(classification_recipe) |> 
  add_model(forest_model) |> 
  fit_resamples(
    compmus_cv, 
    control = control_resamples(save_pred = TRUE)
  )
  
  workflow() |> 
  add_recipe(classification_recipe) |> 
  add_model(forest_model) |> 
  fit(compmus2025_filtered) |> 
  pluck("fit", "fit", "fit") |>
  ranger::importance() |> 
  enframe() |> 
  mutate(name = fct_reorder(name, value)) |> 
  ggplot(aes(name, value)) + 
  geom_col() + 
  coord_flip() +
  theme_minimal() +
  labs(title = "Randomforest classification", x = NULL, y = "Importance")

```

##

```{r}
indie_forest |> get_pr()
```

##

```{r RF graph}
compmus2025_filtered |>
  ggplot(aes(x = valence, y = arousal, colour = ai, size = tempo)) +
  geom_point(alpha = 0.8) +
  scale_color_viridis_d() +
  labs(
    x = "Tempo",
    y = "Danceability",
    size = "Tempo",
    colour = "AI"
  )
```
